"use strict";

const state={csrf:null};
const el=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n};
const fmt=value=>value?new Date(value).toLocaleString("ru-RU",{dateStyle:"short",timeStyle:"short"}):"—";
const badge=value=>{const n=node("span",value,"badge "+String(value).toLowerCase());return n};

async function api(path,options={}){const headers={"Accept":"application/json",...(options.headers||{})};if(options.body){headers["Content-Type"]="application/json"}if(state.csrf&&options.method&&options.method!=="GET")headers["X-CSRF-Token"]=state.csrf;const response=await fetch(path,{credentials:"same-origin",...options,headers});const data=await response.json().catch(()=>({error:"INVALID_RESPONSE"}));if(response.status===401){showLogin();throw new Error("UNAUTHORIZED")}if(!response.ok)throw new Error(data.message||data.error||"Ошибка запроса");return data}
function clear(){el("content").replaceChildren()}
function card(title,wide=false){const c=node("article",undefined,"card "+(wide?"wide":""));c.append(node("h2",title));return c}
function metric(label,value){const m=node("div",undefined,"metric");m.append(node("strong",value),node("span",label));return m}
function showLogin(){el("app").classList.add("hidden");el("login").classList.remove("hidden");state.csrf=null}
function showApp(){el("login").classList.add("hidden");el("app").classList.remove("hidden")}
function title(value){el("page-title").textContent=value;document.title=value+" · Nexora"}
function activate(path){document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.dataset.route===path))}
function errorView(error){clear();const c=card("Не удалось загрузить данные");c.classList.add("full");c.append(node("p",error.message,"danger"));el("content").append(c)}

async function dashboard(){title("Nexora Dashboard");activate("/");const data=await api("/api/health");clear();const grid=node("div",undefined,"grid");const health=card("System Health",true);[["Runtime",data.runtime],["Telegram",data.telegram],["API",data.api],["Database",data.database],["Marketplace",data.marketplace],["Agents",`${data.agents_loaded} loaded`],["Skills",`${data.skills.active}/${data.skills.loaded} active`],["Gateway",data.gateway]].forEach(([k,v])=>{const row=node("div",undefined,"health-row");row.append(node("span",k),node("strong",v,String(v).toLowerCase()==="ok"?"ok":"warning"));health.append(row)});const tasks=card("Tasks Overview");const metrics=node("div",undefined,"metrics");metrics.append(metric("Running",data.tasks.running),metric("Completed today",data.tasks.completed_today),metric("Failed",data.tasks.failed),metric("Waiting approval",data.tasks.waiting_approval));tasks.append(metrics);const agents=card("Platform",true);agents.append(node("p","API, agents, skills и integrations используют Policy Engine и одноразовые approvals.","muted"));const go=node("button","Открыть метрики","secondary");go.onclick=()=>navigate("/metrics");agents.append(go);grid.append(health,tasks,agents);el("content").append(grid)}

async function tasksPage(){title("Задачи");activate("/tasks");clear();const toolbar=node("form",undefined,"toolbar");const search=node("input");search.placeholder="Поиск по ID или названию";const status=node("select");["","IN_PROGRESS","WAITING_APPROVAL","COMPLETED","FAILED","CANCELLED"].forEach(v=>{const o=node("option",v||"Все статусы");o.value=v;status.append(o)});const submit=node("button","Применить","secondary");toolbar.append(search,status,submit);const wrap=node("div",undefined,"table-wrap");el("content").append(toolbar,wrap);async function load(event){if(event)event.preventDefault();const q=new URLSearchParams();if(search.value)q.set("search",search.value);if(status.value)q.set("status",status.value);const data=await api("/api/tasks?"+q);const table=node("table");const head=node("tr");["Task ID","Название","Статус","Прогресс","Агент","Создана"].forEach(x=>head.append(node("th",x)));const thead=node("thead");thead.append(head);const body=node("tbody");data.items.forEach(item=>{const row=node("tr");row.dataset.id=item.id;[item.id,item.title].forEach(x=>row.append(node("td",x)));const s=node("td");s.append(badge(item.status));row.append(s,node("td",`${item.progress}%`),node("td",item.agent),node("td",fmt(item.created_at)));row.onclick=()=>navigate(`/tasks/${encodeURIComponent(item.id)}`);body.append(row)});table.append(thead,body);wrap.replaceChildren(data.items.length?table:node("div","Задач не найдено","empty"))}toolbar.onsubmit=load;await load()}

async function taskPage(id){title("Карточка задачи");activate("/tasks");const item=await api(`/api/tasks/${encodeURIComponent(id)}`);clear();const c=card(`Задача ${item.id}`,true);c.classList.add("full");const details=node("div",undefined,"detail-grid");[["Статус",item.status],["Прогресс",`${item.progress}%`],["Агент",item.agent],["Создана",fmt(item.created_at)],["Обновлена",fmt(item.updated_at)],["Ошибка",item.error_code||"—"]].forEach(([k,v])=>{const d=node("div",undefined,"detail");d.append(node("small",k),node("strong",v));details.append(d)});c.append(details,node("h3","Результат"),node("pre",item.result_summary||"Результат пока отсутствует"),node("h3","События"));item.events.forEach(event=>{const r=node("div",undefined,"health-row");r.append(node("span",event.type),node("small",fmt(event.created_at),"muted"));c.append(r)});el("content").append(c)}

async function agentsPage(){title("Агенты");activate("/agents");const data=await api("/api/agents");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`Risk: ${item.risk}`,"muted"),node("p",`Tools: ${item.tools.join(", ")||"нет"}`));const more=node("button","Подробнее","secondary");more.onclick=()=>navigate(`/agents/${item.id}`);c.append(more);grid.append(c)});el("content").append(grid)}

async function agentPage(id){title("Управление агентом");activate("/agents");const item=await api(`/api/agents/${encodeURIComponent(id)}`);clear();const c=card(item.name,true);c.classList.add("full");c.append(badge(item.status),node("p",item.description),node("h3","Permissions"),node("pre",item.permissions.join("\n")),node("h3","Tools"),node("pre",item.tools.join("\n")),node("h3","Restrictions"),node("pre",item.restrictions.join("\n")));const actions=node("div",undefined,"actions");["enable","disable","reload"].forEach(action=>{const b=node("button",action==="enable"?"Enable":action==="disable"?"Disable":"Reload configuration",action==="disable"?"secondary":"primary");b.onclick=async()=>{b.disabled=true;try{const result=await api(`/api/agents/${id}/actions`,{method:"POST",body:JSON.stringify({action})});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);b.disabled=false}};actions.append(b)});c.append(actions,node("h3","Последние задачи"));item.recent_tasks.forEach(task=>{const r=node("div",undefined,"agent-row");r.append(node("span",task.title),badge(task.status));c.append(r)});el("content").append(c)}

async function skillsPage(){title("Nexora Skills");activate("/skills");const data=await api("/api/skills");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`Version: ${item.version} · Agent: ${item.agent}`,"muted"),node("p",`Risk: ${item.risk}`),node("p",`Tools: ${item.tools.join(", ")}`));const more=node("button","Открыть manifest","secondary");more.onclick=()=>navigate(`/skills/${item.id}`);c.append(more);grid.append(c)});el("content").append(grid)}

async function skillPage(id){title("Управление skill");activate("/skills");const item=await api(`/api/skills/${encodeURIComponent(id)}`);clear();const c=card(item.name,true);c.classList.add("full");c.append(badge(item.status),node("p",item.description),node("h3","Manifest"));const manifest={id:item.id,name:item.name,version:item.version,author:item.author,category:item.category,agent:item.agent,risk:item.risk,sandbox:item.sandbox,approval_required:item.approval_required,permissions:item.permissions,tools:item.tools};c.append(node("pre",JSON.stringify(manifest,null,2)));const actions=node("div",undefined,"actions");[["enable","Enable","primary"],["disable","Disable","secondary"],["reload","Reload","primary"]].forEach(([action,label,cls])=>{const b=node("button",label,cls);b.onclick=async()=>{b.disabled=true;try{const result=await api(`/api/skills/${id}/${action}`,{method:"POST",body:"{}"});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);b.disabled=false}};actions.append(b)});c.append(actions,node("h3","Lifecycle"));item.events.forEach(event=>{const r=node("div",undefined,"health-row");r.append(node("span",event.event),node("small",`${event.result} · ${fmt(event.created_at)}`,"muted"));c.append(r)});el("content").append(c)}

async function templatesPage(){title("Workflow Templates");activate("/templates");const data=await api("/api/templates");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`Version: ${item.version} · Agents: ${item.agents.length} · Skills: ${item.skills.length}`,"muted"),node("p",`Risk: ${item.risk}`));const more=node("button","Inspect","secondary");more.onclick=()=>navigate(`/templates/${item.id}`);c.append(more);grid.append(c)});el("content").append(grid)}

async function templatePage(id){title("Template details");activate("/templates");const item=await api(`/api/templates/${encodeURIComponent(id)}`);clear();const c=card(item.name,true);c.classList.add("full");c.append(badge(item.status),node("p",item.description),node("h3","Manifest"),node("pre",JSON.stringify({id:item.id,version:item.version,agents:item.agents,skills:item.skills,permissions:item.permissions,approval_required:item.approval_required},null,2)));const install=node("button",item.approval_required?"Install with approval":"Install","primary");install.disabled=item.status!=="ACTIVE";install.onclick=async()=>{install.disabled=true;try{const result=await api(`/api/templates/${id}/install`,{method:"POST",body:"{}"});if(result.approval_id){alert(`Approval created: ${result.approval_id}`);navigate("/approvals")}else{alert("Template installed");navigate("/templates")}}catch(e){alert(e.message);install.disabled=false}};c.append(install);el("content").append(c)}

async function playgroundPage(){title("Safe Playground");activate("/playground");const data=await api("/api/playground/examples");clear();const notice=card("Sandbox-only examples",true);notice.classList.add("full");notice.append(node("p","No external writes, publishing, secrets, or production tools are available.","muted"));const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(node("p",`Agent: ${item.agent} · Input: ${item.input_type}`,"muted"),badge(data.mode));grid.append(c)});el("content").append(notice,grid)}

async function organizationsPage(){title("Organizations");activate("/organizations");const data=await api("/api/organizations");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`ID: ${item.id}`,"muted"));grid.append(c)});el("content").append(grid)}

async function workspacesPage(){title("Workspaces");activate("/workspaces");const data=await api("/api/workspaces");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",item.description||"No description"),node("p",`Members: ${item.members} · Agents: ${item.agents} · Tasks: ${item.tasks} · Skills: ${item.skills}`,"muted"),node("p",`Role: ${item.role}`,"muted"));grid.append(c)});el("content").append(grid)}

async function membersPage(){title("Members");activate("/members");const workspaces=await api("/api/workspaces");clear();if(!workspaces.items.length){el("content").append(node("div","No accessible workspace","empty"));return}const workspace=workspaces.items[0];const data=await api(`/api/members?workspace_id=${encodeURIComponent(workspace.id)}`);const c=card(`${workspace.name} members`,true);c.classList.add("full");data.items.forEach(item=>{const row=node("div",undefined,"health-row");row.append(node("span",item.display_name),badge(item.role));c.append(row)});el("content").append(c)}

async function knowledgePage(){title("Knowledge Base");activate("/knowledge");const workspaces=await api("/api/workspaces");clear();if(!workspaces.items.length){el("content").append(node("div","No accessible workspace","empty"));return}const workspace=workspaces.items[0];const data=await api(`/api/knowledge?workspace_id=${encodeURIComponent(workspace.id)}`);const c=card(`${workspace.name} knowledge`,true);c.classList.add("full");if(!data.items.length)c.append(node("div","Knowledge documents not found","empty"));data.items.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.name),node("p",`${item.type} · ${item.access_level}`,"muted"));row.append(info);c.append(row)});el("content").append(c)}

function choice(name,value,label){const wrap=node("label",undefined,"choice");const input=node("input");input.type="checkbox";input.name=name;input.value=value;wrap.append(input,node("span",label));return wrap}

async function apiKeysPage(){title("API Keys");activate("/api-keys");clear();const form=card("Создать API key",true);const name=node("input");name.placeholder="Название ключа";name.maxLength=100;const expiry=node("input");expiry.type="datetime-local";const scopes=node("div",undefined,"actions");["tasks:create","tasks:read","agents:read","skills:read","webhooks:manage"].forEach(scope=>scopes.append(choice("scope",scope,scope)));const create=node("button","Создать через approval","primary");form.append(name,expiry,scopes,create);create.onclick=async()=>{create.disabled=true;try{const selected=[...scopes.querySelectorAll("input:checked")].map(x=>x.value);const expires_at=expiry.value?new Date(expiry.value).toISOString():null;const result=await api("/api/platform/api-keys",{method:"POST",body:JSON.stringify({name:name.value,scopes:selected,expires_at})});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);create.disabled=false}};const list=card("Ключи",true);list.classList.add("full");const data=await api("/api/platform/api-keys");if(!data.items.length)list.append(node("div","API keys пока нет","empty"));data.items.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.name),node("p",`${item.id} · ${item.scopes.join(", ")} · expires ${fmt(item.expires_at)}`,"muted"));row.append(info,badge(item.status));if(item.status!=="PENDING"){const actions=node("div",undefined,"actions");[["disable","Disable"],["delete","Delete"]].forEach(([action,label])=>{const b=node("button",label,"secondary");b.onclick=async()=>{const result=await api(`/api/platform/api-keys/${item.id}/${action}`,{method:"POST",body:"{}"});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")};actions.append(b)});row.append(actions)}list.append(row)});el("content").append(form,list)}

async function webhooksPage(){title("Webhooks");activate("/webhooks");clear();const form=card("Новый webhook",true);const url=node("input");url.placeholder="https://example.com/nexora-events";const events=node("div",undefined,"actions");["TASK_CREATED","TASK_COMPLETED","TASK_FAILED","APPROVAL_REQUIRED","SECURITY_EVENT"].forEach(event=>events.append(choice("event",event,event)));const create=node("button","Добавить через approval","primary");form.append(url,events,create);create.onclick=async()=>{create.disabled=true;try{const selected=[...events.querySelectorAll("input:checked")].map(x=>x.value);const result=await api("/api/platform/webhooks",{method:"POST",body:JSON.stringify({url:url.value,events:selected})});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);create.disabled=false}};const list=card("Webhook endpoints",true);list.classList.add("full");const data=await api("/api/platform/webhooks");if(!data.items.length)list.append(node("div","Webhooks пока нет","empty"));data.items.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.url),node("p",`${item.id} · ${item.events.join(", ")} · failures ${item.failure_count}`,"muted"));row.append(info,badge(item.status));if(item.status!=="PENDING"){const actions=node("div",undefined,"actions");[["disable","Disable"],["delete","Delete"]].forEach(([action,label])=>{const b=node("button",label,"secondary");b.onclick=async()=>{const result=await api(`/api/platform/webhooks/${item.id}/${action}`,{method:"POST",body:"{}"});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")};actions.append(b)});row.append(actions)}list.append(row)});el("content").append(form,list)}

async function metricsPage(){title("Metrics");activate("/metrics");const data=await api("/api/platform/metrics");clear();const c=card("Usage metrics",true);c.classList.add("full");const values=node("div",undefined,"metrics");values.append(metric("Tasks today",data.tasks_today),metric("Success",`${data.success_percent}%`),metric("Average",`${data.average_seconds}s`),metric("Active agents",data.active_agents));c.append(values,node("h3","Agents"));data.agents.forEach(item=>{const r=node("div",undefined,"health-row");r.append(node("span",item.agent),node("strong",`${item.uses} uses · ${item.errors} errors`));c.append(r)});el("content").append(c)}

async function integrationsPage(){title("Integrations");activate("/integrations");const data=await api("/api/platform/integrations");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.id);c.append(badge(item.status),node("pre",JSON.stringify(item,null,2)));grid.append(c)});el("content").append(grid)}

async function approvalsPage(){title("Approval Center");activate("/approvals");const data=await api("/api/approvals");clear();const c=card("Подтверждения",true);c.classList.add("full");if(!data.items.length)c.append(node("div","Подтверждений пока нет","empty"));data.items.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.action_summary||item.action_type),node("p",`Task: ${item.task_id} · Истекает: ${fmt(item.expires_at)}`,"muted"));row.append(info,badge(item.status));if(item.status==="PENDING"){const actions=node("div",undefined,"actions");[["approve","Approve","primary"],["reject","Reject","secondary"]].forEach(([decision,label,cls])=>{const b=node("button",label,cls);b.onclick=async()=>{b.disabled=true;try{const result=await api(`/api/approvals/${item.id}/${decision}`,{method:"POST",body:"{}"});if(result.one_time_secret)window.prompt(result.secret_notice,result.one_time_secret);await approvalsPage()}catch(e){alert(e.message);b.disabled=false}};actions.append(b)});row.append(actions)}c.append(row)});el("content").append(c)}

async function auditPage(){title("Audit Viewer");activate("/audit");clear();const toolbar=node("form",undefined,"toolbar");const severity=node("select");["","INFO","WARNING","SECURITY","ERROR"].forEach(v=>{const o=node("option",v||"Все уровни");o.value=v;severity.append(o)});const source=node("input");source.placeholder="Source";const event=node("input");event.placeholder="Event type";const date=node("input");date.type="date";toolbar.append(severity,source,event,date,node("button","Фильтр","secondary"));const wrap=node("div",undefined,"table-wrap");el("content").append(toolbar,wrap);async function load(e){if(e)e.preventDefault();const q=new URLSearchParams();[["severity",severity.value],["source",source.value],["event",event.value],["date",date.value]].forEach(([k,v])=>{if(v)q.set(k,v)});const data=await api("/api/audit?"+q);const table=node("table");const head=node("tr");["Severity","Event","Source","Result","Time"].forEach(x=>head.append(node("th",x)));const thead=node("thead");thead.append(head);const body=node("tbody");data.items.forEach(item=>{const row=node("tr");const s=node("td");s.append(badge(item.severity));row.append(s,node("td",item.event),node("td",item.source),node("td",item.result),node("td",fmt(item.created_at)));body.append(row)});table.append(thead,body);wrap.replaceChildren(table)}toolbar.onsubmit=load;await load()}

async function route(){try{const path=location.pathname;if(path==="/")await dashboard();else if(path==="/tasks")await tasksPage();else if(path.startsWith("/tasks/"))await taskPage(decodeURIComponent(path.slice(7)));else if(path==="/agents")await agentsPage();else if(path.startsWith("/agents/"))await agentPage(decodeURIComponent(path.slice(8)));else if(path==="/skills")await skillsPage();else if(path.startsWith("/skills/"))await skillPage(decodeURIComponent(path.slice(8)));else if(path==="/api-keys")await apiKeysPage();else if(path==="/webhooks")await webhooksPage();else if(path==="/metrics")await metricsPage();else if(path==="/integrations")await integrationsPage();else if(path==="/approvals")await approvalsPage();else if(path==="/audit")await auditPage();else navigate("/")}catch(error){if(error.message!=="UNAUTHORIZED")errorView(error)}}
const metricsPageV18=metricsPage;
metricsPage=async function(){await metricsPageV18();const data=await api("/api/platform/metrics");const community=card("Community metrics",true);community.classList.add("full");const values=node("div",undefined,"metrics");values.append(metric("Installed templates",data.community.installed_templates),metric("Active skills",data.community.active_skills),metric("Completed demos",data.community.completed_demos));community.append(values);el("content").append(community)};
const apiKeysPageV18=apiKeysPage;
apiKeysPage=async function(){await apiKeysPageV18();const values=["templates:read","templates:install","playground:read","organizations:read","workspaces:read","workspaces:write","members:read","members:invite","knowledge:read","knowledge:write","plans:read","billing:read","usage:read","limits:read","marketplace:read","marketplace:install","marketplace:publish","creators:read","creator:read"];const last=document.querySelector('input[name="scope"][value="webhooks:manage"]');const container=last&&last.closest(".actions");if(container)values.forEach(scope=>container.append(choice("scope",scope,scope)))};
const routeV20=route;
route=async function(){const path=location.pathname;try{if(path==="/templates")return await templatesPage();if(path.startsWith("/templates/"))return await templatePage(decodeURIComponent(path.slice(11)));if(path==="/playground")return await playgroundPage();return await routeV20()}catch(error){if(error.message!=="UNAUTHORIZED")errorView(error)}};
const routeV21=route;
route=async function(){const path=location.pathname;try{if(path==="/organizations")return await organizationsPage();if(path==="/workspaces")return await workspacesPage();if(path==="/members")return await membersPage();if(path==="/knowledge")return await knowledgePage();return await routeV21()}catch(error){if(error.message!=="UNAUTHORIZED")errorView(error)}};
async function plansPage(){title("Plans");activate("/plans");const data=await api("/api/plans");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`Tier: ${item.tier}`),node("pre",JSON.stringify({limits:item.limits,features:item.features},null,2)));grid.append(c)});el("content").append(grid)}
async function billingPage(){title("Billing");activate("/billing");const data=await api("/api/billing");clear();const c=card(`Current Plan: ${data.subscription.plan_name}`,true);c.classList.add("full");c.append(badge(data.subscription.status),node("h3","Usage and limits"));Object.entries(data.limits.limits).forEach(([key,value])=>{const row=node("div",undefined,"health-row");const current=data.limits.current[key]||0;row.append(node("span",key),node("strong",`${current} / ${value===null?"Unlimited":value}`));c.append(row)});el("content").append(c)}
async function usagePage(){title("Usage");activate("/usage");const data=await api("/api/usage-v23");clear();const c=card(`Usage ${data.month}`,true);c.classList.add("full");c.append(node("h3","Metered events"),node("pre",JSON.stringify(data.events,null,2)),node("h3","Current resources"),node("pre",JSON.stringify(data.resources,null,2)));el("content").append(c)}
async function adminPage(){title("Admin Console");activate("/admin");const data=await api("/api/admin");clear();const health=card("System Health",true);health.append(node("pre",JSON.stringify(data.system_health,null,2)));const c=card("Organizations / Subscriptions / Usage / Limits",true);c.classList.add("full");data.organizations.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.name),node("p",`${item.id} · ${item.plan_id} · ${item.subscription_status}`,"muted"),node("p",`Tasks: ${item.usage.resources.tasks_monthly} · Workspaces: ${item.usage.resources.workspace_limit}`,"muted"));const actions=node("div",undefined,"actions");const plan=node("select");data.plans.forEach(value=>{const option=node("option",value.name);option.value=value.id;plan.append(option)});const change=node("button","Change plan","primary");change.onclick=async()=>{const result=await api(`/api/admin/organizations/${item.id}/plan`,{method:"POST",body:JSON.stringify({plan_id:plan.value})});alert(`Approval created: ${result.approval_id}`);navigate("/approvals")};const block=node("button",item.status==="SUSPENDED"?"Unblock":"Block","secondary");block.onclick=async()=>{const action=item.status==="SUSPENDED"?"unblock":"block";const result=await api(`/api/admin/organizations/${item.id}/${action}`,{method:"POST",body:"{}"});alert(`Approval created: ${result.approval_id}`);navigate("/approvals")};actions.append(plan,change,block);row.append(info,actions);c.append(row)});const security=card("Security Events",true);security.classList.add("full");security.append(node("pre",JSON.stringify(data.security_events,null,2)));el("content").append(health,c,security)}
const routeV22=route;
route=async function(){const path=location.pathname;try{if(path==="/plans")return await plansPage();if(path==="/billing")return await billingPage();if(path==="/usage")return await usagePage();if(path==="/admin")return await adminPage();return await routeV22()}catch(error){if(error.message!=="UNAUTHORIZED")errorView(error)}};
async function marketplacePage(){title("Marketplace");activate("/marketplace");const data=await api("/api/marketplace");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`${item.type} · ${item.version} · ${item.author}`,"muted"),node("p",item.description),node("p",`Risk: ${item.risk_level} · Downloads: ${item.downloads}`));const open=node("button","View package","secondary");open.onclick=()=>navigate(`/marketplace/${item.id}`);c.append(open);grid.append(c)});el("content").append(data.items.length?grid:node("div","Marketplace catalog is empty","empty"))}
async function marketplaceItemPage(id){title("Marketplace item");activate("/marketplace");const item=await api(`/api/marketplace/${encodeURIComponent(id)}`);const workspaces=await api("/api/workspaces");clear();const c=card(item.name,true);c.classList.add("full");c.append(badge(item.status),node("p",item.description),node("pre",JSON.stringify({type:item.type,version:item.version,author:item.author,risk:item.risk_level,permissions:item.manifest.permissions,security:item.manifest.security,checksum:item.checksum,signature_status:item.signature_status},null,2)));if(workspaces.items.length){const select=node("select");workspaces.items.forEach(ws=>{const o=node("option",ws.name);o.value=ws.id;select.append(o)});const install=node("button","Install","primary");install.onclick=async()=>{install.disabled=true;try{const result=await api(`/api/marketplace/${id}/install`,{method:"POST",body:JSON.stringify({workspace_id:select.value,version:item.version})});if(result.approval_id){alert(`Approval created: ${result.approval_id}`);navigate("/approvals")}else{alert("Installed")}}catch(e){alert(e.message);install.disabled=false}};c.append(select,install)}el("content").append(c)}
async function myItemsPage(){title("My marketplace items");activate("/my-items");const data=await api("/api/my-items");clear();const c=card("Published items",true);c.classList.add("full");data.items.forEach(item=>{const row=node("div",undefined,"health-row");row.append(node("span",`${item.name} ${item.version}`),badge(item.status));c.append(row)});if(!data.items.length)c.append(node("div","No published items","empty"));el("content").append(c)}
async function publisherPage(){title("Publisher");activate("/publisher");const data=await api("/api/publisher");clear();const form=card("Register publisher",true);const name=node("input");name.placeholder="Publisher display name";const register=node("button","Register with approval","primary");register.onclick=async()=>{register.disabled=true;try{const result=await api("/api/publisher/register",{method:"POST",body:JSON.stringify({display_name:name.value})});alert(`Approval created: ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);register.disabled=false}};form.append(name,register);const list=card("Publisher identities",true);data.publishers.forEach(item=>{const row=node("div",undefined,"health-row");row.append(node("span",item.display_name),badge(item.status));list.append(row)});el("content").append(form,list)}
async function creatorPage(){title("Creator Dashboard");activate("/creator");const data=await api("/api/creator");clear();if(!data.configured){const form=card("Create creator profile",true);const name=node("input");name.placeholder="Display name";const bio=node("input");bio.placeholder="Bio";const create=node("button","Create profile","primary");create.onclick=async()=>{create.disabled=true;try{await api("/api/creator/profile",{method:"POST",body:JSON.stringify({display_name:name.value,bio:bio.value})});await creatorPage()}catch(e){alert(e.message);create.disabled=false}};form.append(name,bio,create);el("content").append(form);return}const p=data.profile;const profile=card(p.display_name,true);profile.append(badge(p.status),node("p",p.bio||"No bio","muted"),node("p",`Verification: ${p.level||"NEW_CREATOR"}`));const metrics=card("Analytics",true);const s=data.analytics.summary;metrics.append(node("p",`Packages: ${s.packages} · Installs: ${s.total_installs} · Active: ${s.active_installations}`),node("p",`Executions: ${s.executions} · Success: ${s.success_rate}% · Rating: ${s.rating}`));const packages=card("My Packages",true);data.packages.forEach(item=>{const row=node("div",undefined,"health-row");row.append(node("span",`${item.package_id} ${item.version}`),badge(item.status));packages.append(row)});if(!data.packages.length)packages.append(node("div","No packages","empty"));const sections=card("Creator tools",true);sections.append(node("p","My Packages · Analytics · Reviews · Verification · Settings","muted"));el("content").append(profile,metrics,packages,sections)}
const routeV23=route;
route=async function(){const path=location.pathname;try{if(path==="/marketplace")return await marketplacePage();if(path.startsWith("/marketplace/"))return await marketplaceItemPage(decodeURIComponent(path.slice(13)));if(path==="/my-items")return await myItemsPage();if(path==="/publisher")return await publisherPage();if(path==="/creator")return await creatorPage();return await routeV23()}catch(error){if(error.message!=="UNAUTHORIZED")errorView(error)}};
function navigate(path){history.pushState({},"",path);route()}
document.addEventListener("click",event=>{const link=event.target.closest("a[data-route]");if(link){event.preventDefault();navigate(link.getAttribute("href"))}});window.addEventListener("popstate",route);
el("login-form").addEventListener("submit",async event=>{event.preventDefault();el("login-error").textContent="";const data=Object.fromEntries(new FormData(event.target));try{const result=await api("/api/login",{method:"POST",body:JSON.stringify(data)});state.csrf=result.csrf_token;event.target.reset();showApp();route()}catch(error){el("login-error").textContent=error.message==="UNAUTHORIZED"?"Неверные данные или доступ временно ограничен.":error.message}});
el("logout").onclick=async()=>{try{await api("/api/logout",{method:"POST",body:"{}"})}finally{showLogin()}};
(async()=>{try{const session=await api("/api/session");state.csrf=session.csrf_token;showApp();route()}catch{showLogin()}})();
