"use strict";

const state={csrf:null};
const el=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n};
const fmt=value=>value?new Date(value).toLocaleString("ru-RU",{dateStyle:"short",timeStyle:"short"}):"—";
const badge=value=>{const n=node("span",value,"badge "+String(value).toLowerCase());return n};

async function api(path,options={}){const headers={"Accept":"application/json",...(options.headers||{})};if(options.body){headers["Content-Type"]="application/json"}if(state.csrf&&options.method&&options.method!=="GET")headers["X-CSRF-Token"]=state.csrf;const response=await fetch(path,{credentials:"same-origin",...options,headers});const data=await response.json().catch(()=>({error:"INVALID_RESPONSE"}));if(response.status===401){showLogin();throw new Error("UNAUTHORIZED")}if(!response.ok)throw new Error(data.message||data.error||"Ошибка запроса");return data}
function clear(){el("content").replaceChildren()}
function card(title,wide=false){const c=node("article",undefined,"card "+(wide?"wide":""));c.append(node("h2",title));return c}
function metric(label,value){const m=node("div",undefined,"metric");m.append(node("strong",value),node("span",label));return m}
function showLogin(){el("app").classList.add("hidden");el("login").classList.remove("hidden");state.csrf=null}
function showApp(){el("login").classList.add("hidden");el("app").classList.remove("hidden")}
function title(value){el("page-title").textContent=value;document.title=value+" · Nexora"}
function activate(path){document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.dataset.route===path))}
function errorView(error){clear();const c=card("Не удалось загрузить данные");c.classList.add("full");c.append(node("p",error.message,"danger"));el("content").append(c)}

async function dashboard(){title("Nexora Dashboard");activate("/");const data=await api("/api/health");clear();const grid=node("div",undefined,"grid");const health=card("System Health",true);[["Runtime",data.runtime],["Telegram",data.telegram],["API",data.api],["Database",data.database],["Agents",`${data.agents_loaded} loaded`],["Skills",`${data.skills.active}/${data.skills.loaded} active`],["Gateway",data.gateway]].forEach(([k,v])=>{const row=node("div",undefined,"health-row");row.append(node("span",k),node("strong",v,String(v).toLowerCase()==="ok"?"ok":"warning"));health.append(row)});const tasks=card("Tasks Overview");const metrics=node("div",undefined,"metrics");metrics.append(metric("Running",data.tasks.running),metric("Completed today",data.tasks.completed_today),metric("Failed",data.tasks.failed),metric("Waiting approval",data.tasks.waiting_approval));tasks.append(metrics);const agents=card("Platform",true);agents.append(node("p","API, agents, skills и integrations используют Policy Engine и одноразовые approvals.","muted"));const go=node("button","Открыть метрики","secondary");go.onclick=()=>navigate("/metrics");agents.append(go);grid.append(health,tasks,agents);el("content").append(grid)}

async function tasksPage(){title("Задачи");activate("/tasks");clear();const toolbar=node("form",undefined,"toolbar");const search=node("input");search.placeholder="Поиск по ID или названию";const status=node("select");["","IN_PROGRESS","WAITING_APPROVAL","COMPLETED","FAILED","CANCELLED"].forEach(v=>{const o=node("option",v||"Все статусы");o.value=v;status.append(o)});const submit=node("button","Применить","secondary");toolbar.append(search,status,submit);const wrap=node("div",undefined,"table-wrap");el("content").append(toolbar,wrap);async function load(event){if(event)event.preventDefault();const q=new URLSearchParams();if(search.value)q.set("search",search.value);if(status.value)q.set("status",status.value);const data=await api("/api/tasks?"+q);const table=node("table");const head=node("tr");["Task ID","Название","Статус","Прогресс","Агент","Создана"].forEach(x=>head.append(node("th",x)));const thead=node("thead");thead.append(head);const body=node("tbody");data.items.forEach(item=>{const row=node("tr");row.dataset.id=item.id;[item.id,item.title].forEach(x=>row.append(node("td",x)));const s=node("td");s.append(badge(item.status));row.append(s,node("td",`${item.progress}%`),node("td",item.agent),node("td",fmt(item.created_at)));row.onclick=()=>navigate(`/tasks/${encodeURIComponent(item.id)}`);body.append(row)});table.append(thead,body);wrap.replaceChildren(data.items.length?table:node("div","Задач не найдено","empty"))}toolbar.onsubmit=load;await load()}

async function taskPage(id){title("Карточка задачи");activate("/tasks");const item=await api(`/api/tasks/${encodeURIComponent(id)}`);clear();const c=card(`Задача ${item.id}`,true);c.classList.add("full");const details=node("div",undefined,"detail-grid");[["Статус",item.status],["Прогресс",`${item.progress}%`],["Агент",item.agent],["Создана",fmt(item.created_at)],["Обновлена",fmt(item.updated_at)],["Ошибка",item.error_code||"—"]].forEach(([k,v])=>{const d=node("div",undefined,"detail");d.append(node("small",k),node("strong",v));details.append(d)});c.append(details,node("h3","Результат"),node("pre",item.result_summary||"Результат пока отсутствует"),node("h3","События"));item.events.forEach(event=>{const r=node("div",undefined,"health-row");r.append(node("span",event.type),node("small",fmt(event.created_at),"muted"));c.append(r)});el("content").append(c)}

async function agentsPage(){title("Агенты");activate("/agents");const data=await api("/api/agents");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`Risk: ${item.risk}`,"muted"),node("p",`Tools: ${item.tools.join(", ")||"нет"}`));const more=node("button","Подробнее","secondary");more.onclick=()=>navigate(`/agents/${item.id}`);c.append(more);grid.append(c)});el("content").append(grid)}

async function agentPage(id){title("Управление агентом");activate("/agents");const item=await api(`/api/agents/${encodeURIComponent(id)}`);clear();const c=card(item.name,true);c.classList.add("full");c.append(badge(item.status),node("p",item.description),node("h3","Permissions"),node("pre",item.permissions.join("\n")),node("h3","Tools"),node("pre",item.tools.join("\n")),node("h3","Restrictions"),node("pre",item.restrictions.join("\n")));const actions=node("div",undefined,"actions");["enable","disable","reload"].forEach(action=>{const b=node("button",action==="enable"?"Enable":action==="disable"?"Disable":"Reload configuration",action==="disable"?"secondary":"primary");b.onclick=async()=>{b.disabled=true;try{const result=await api(`/api/agents/${id}/actions`,{method:"POST",body:JSON.stringify({action})});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);b.disabled=false}};actions.append(b)});c.append(actions,node("h3","Последние задачи"));item.recent_tasks.forEach(task=>{const r=node("div",undefined,"agent-row");r.append(node("span",task.title),badge(task.status));c.append(r)});el("content").append(c)}

async function skillsPage(){title("Nexora Skills");activate("/skills");const data=await api("/api/skills");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.name);c.append(badge(item.status),node("p",`Version: ${item.version} · Agent: ${item.agent}`,"muted"),node("p",`Risk: ${item.risk}`),node("p",`Tools: ${item.tools.join(", ")}`));const more=node("button","Открыть manifest","secondary");more.onclick=()=>navigate(`/skills/${item.id}`);c.append(more);grid.append(c)});el("content").append(grid)}

async function skillPage(id){title("Управление skill");activate("/skills");const item=await api(`/api/skills/${encodeURIComponent(id)}`);clear();const c=card(item.name,true);c.classList.add("full");c.append(badge(item.status),node("p",item.description),node("h3","Manifest"));const manifest={id:item.id,name:item.name,version:item.version,author:item.author,category:item.category,agent:item.agent,risk:item.risk,sandbox:item.sandbox,approval_required:item.approval_required,permissions:item.permissions,tools:item.tools};c.append(node("pre",JSON.stringify(manifest,null,2)));const actions=node("div",undefined,"actions");[["enable","Enable","primary"],["disable","Disable","secondary"],["reload","Reload","primary"]].forEach(([action,label,cls])=>{const b=node("button",label,cls);b.onclick=async()=>{b.disabled=true;try{const result=await api(`/api/skills/${id}/${action}`,{method:"POST",body:"{}"});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);b.disabled=false}};actions.append(b)});c.append(actions,node("h3","Lifecycle"));item.events.forEach(event=>{const r=node("div",undefined,"health-row");r.append(node("span",event.event),node("small",`${event.result} · ${fmt(event.created_at)}`,"muted"));c.append(r)});el("content").append(c)}

function choice(name,value,label){const wrap=node("label",undefined,"choice");const input=node("input");input.type="checkbox";input.name=name;input.value=value;wrap.append(input,node("span",label));return wrap}

async function apiKeysPage(){title("API Keys");activate("/api-keys");clear();const form=card("Создать API key",true);const name=node("input");name.placeholder="Название ключа";name.maxLength=100;const expiry=node("input");expiry.type="datetime-local";const scopes=node("div",undefined,"actions");["tasks:create","tasks:read","agents:read","skills:read","webhooks:manage"].forEach(scope=>scopes.append(choice("scope",scope,scope)));const create=node("button","Создать через approval","primary");form.append(name,expiry,scopes,create);create.onclick=async()=>{create.disabled=true;try{const selected=[...scopes.querySelectorAll("input:checked")].map(x=>x.value);const expires_at=expiry.value?new Date(expiry.value).toISOString():null;const result=await api("/api/platform/api-keys",{method:"POST",body:JSON.stringify({name:name.value,scopes:selected,expires_at})});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);create.disabled=false}};const list=card("Ключи",true);list.classList.add("full");const data=await api("/api/platform/api-keys");if(!data.items.length)list.append(node("div","API keys пока нет","empty"));data.items.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.name),node("p",`${item.id} · ${item.scopes.join(", ")} · expires ${fmt(item.expires_at)}`,"muted"));row.append(info,badge(item.status));if(item.status!=="PENDING"){const actions=node("div",undefined,"actions");[["disable","Disable"],["delete","Delete"]].forEach(([action,label])=>{const b=node("button",label,"secondary");b.onclick=async()=>{const result=await api(`/api/platform/api-keys/${item.id}/${action}`,{method:"POST",body:"{}"});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")};actions.append(b)});row.append(actions)}list.append(row)});el("content").append(form,list)}

async function webhooksPage(){title("Webhooks");activate("/webhooks");clear();const form=card("Новый webhook",true);const url=node("input");url.placeholder="https://example.com/nexora-events";const events=node("div",undefined,"actions");["TASK_CREATED","TASK_COMPLETED","TASK_FAILED","APPROVAL_REQUIRED","SECURITY_EVENT"].forEach(event=>events.append(choice("event",event,event)));const create=node("button","Добавить через approval","primary");form.append(url,events,create);create.onclick=async()=>{create.disabled=true;try{const selected=[...events.querySelectorAll("input:checked")].map(x=>x.value);const result=await api("/api/platform/webhooks",{method:"POST",body:JSON.stringify({url:url.value,events:selected})});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")}catch(e){alert(e.message);create.disabled=false}};const list=card("Webhook endpoints",true);list.classList.add("full");const data=await api("/api/platform/webhooks");if(!data.items.length)list.append(node("div","Webhooks пока нет","empty"));data.items.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.url),node("p",`${item.id} · ${item.events.join(", ")} · failures ${item.failure_count}`,"muted"));row.append(info,badge(item.status));if(item.status!=="PENDING"){const actions=node("div",undefined,"actions");[["disable","Disable"],["delete","Delete"]].forEach(([action,label])=>{const b=node("button",label,"secondary");b.onclick=async()=>{const result=await api(`/api/platform/webhooks/${item.id}/${action}`,{method:"POST",body:"{}"});alert(`Создано подтверждение ${result.approval_id}`);navigate("/approvals")};actions.append(b)});row.append(actions)}list.append(row)});el("content").append(form,list)}

async function metricsPage(){title("Metrics");activate("/metrics");const data=await api("/api/platform/metrics");clear();const c=card("Usage metrics",true);c.classList.add("full");const values=node("div",undefined,"metrics");values.append(metric("Tasks today",data.tasks_today),metric("Success",`${data.success_percent}%`),metric("Average",`${data.average_seconds}s`),metric("Active agents",data.active_agents));c.append(values,node("h3","Agents"));data.agents.forEach(item=>{const r=node("div",undefined,"health-row");r.append(node("span",item.agent),node("strong",`${item.uses} uses · ${item.errors} errors`));c.append(r)});el("content").append(c)}

async function integrationsPage(){title("Integrations");activate("/integrations");const data=await api("/api/platform/integrations");clear();const grid=node("div",undefined,"grid");data.items.forEach(item=>{const c=card(item.id);c.append(badge(item.status),node("pre",JSON.stringify(item,null,2)));grid.append(c)});el("content").append(grid)}

async function approvalsPage(){title("Approval Center");activate("/approvals");const data=await api("/api/approvals");clear();const c=card("Подтверждения",true);c.classList.add("full");if(!data.items.length)c.append(node("div","Подтверждений пока нет","empty"));data.items.forEach(item=>{const row=node("div",undefined,"approval-row");const info=node("div");info.append(node("strong",item.action_summary||item.action_type),node("p",`Task: ${item.task_id} · Истекает: ${fmt(item.expires_at)}`,"muted"));row.append(info,badge(item.status));if(item.status==="PENDING"){const actions=node("div",undefined,"actions");[["approve","Approve","primary"],["reject","Reject","secondary"]].forEach(([decision,label,cls])=>{const b=node("button",label,cls);b.onclick=async()=>{b.disabled=true;try{const result=await api(`/api/approvals/${item.id}/${decision}`,{method:"POST",body:"{}"});if(result.one_time_secret)window.prompt(result.secret_notice,result.one_time_secret);await approvalsPage()}catch(e){alert(e.message);b.disabled=false}};actions.append(b)});row.append(actions)}c.append(row)});el("content").append(c)}

async function auditPage(){title("Audit Viewer");activate("/audit");clear();const toolbar=node("form",undefined,"toolbar");const severity=node("select");["","INFO","WARNING","SECURITY","ERROR"].forEach(v=>{const o=node("option",v||"Все уровни");o.value=v;severity.append(o)});const source=node("input");source.placeholder="Source";const event=node("input");event.placeholder="Event type";const date=node("input");date.type="date";toolbar.append(severity,source,event,date,node("button","Фильтр","secondary"));const wrap=node("div",undefined,"table-wrap");el("content").append(toolbar,wrap);async function load(e){if(e)e.preventDefault();const q=new URLSearchParams();[["severity",severity.value],["source",source.value],["event",event.value],["date",date.value]].forEach(([k,v])=>{if(v)q.set(k,v)});const data=await api("/api/audit?"+q);const table=node("table");const head=node("tr");["Severity","Event","Source","Result","Time"].forEach(x=>head.append(node("th",x)));const thead=node("thead");thead.append(head);const body=node("tbody");data.items.forEach(item=>{const row=node("tr");const s=node("td");s.append(badge(item.severity));row.append(s,node("td",item.event),node("td",item.source),node("td",item.result),node("td",fmt(item.created_at)));body.append(row)});table.append(thead,body);wrap.replaceChildren(table)}toolbar.onsubmit=load;await load()}

async function route(){try{const path=location.pathname;if(path==="/")await dashboard();else if(path==="/tasks")await tasksPage();else if(path.startsWith("/tasks/"))await taskPage(decodeURIComponent(path.slice(7)));else if(path==="/agents")await agentsPage();else if(path.startsWith("/agents/"))await agentPage(decodeURIComponent(path.slice(8)));else if(path==="/skills")await skillsPage();else if(path.startsWith("/skills/"))await skillPage(decodeURIComponent(path.slice(8)));else if(path==="/api-keys")await apiKeysPage();else if(path==="/webhooks")await webhooksPage();else if(path==="/metrics")await metricsPage();else if(path==="/integrations")await integrationsPage();else if(path==="/approvals")await approvalsPage();else if(path==="/audit")await auditPage();else navigate("/")}catch(error){if(error.message!=="UNAUTHORIZED")errorView(error)}}
function navigate(path){history.pushState({},"",path);route()}
document.addEventListener("click",event=>{const link=event.target.closest("a[data-route]");if(link){event.preventDefault();navigate(link.getAttribute("href"))}});window.addEventListener("popstate",route);
el("login-form").addEventListener("submit",async event=>{event.preventDefault();el("login-error").textContent="";const data=Object.fromEntries(new FormData(event.target));try{const result=await api("/api/login",{method:"POST",body:JSON.stringify(data)});state.csrf=result.csrf_token;event.target.reset();showApp();route()}catch(error){el("login-error").textContent=error.message==="UNAUTHORIZED"?"Неверные данные или доступ временно ограничен.":error.message}});
el("logout").onclick=async()=>{try{await api("/api/logout",{method:"POST",body:"{}"})}finally{showLogin()}};
(async()=>{try{const session=await api("/api/session");state.csrf=session.csrf_token;showApp();route()}catch{showLogin()}})();
