"""Safe, deterministic renderers for task-result document artifacts.

The renderers operate entirely in memory, never execute user content, never
resolve user-provided paths, and produce only allowlisted non-executable
formats.  Rich formats are derived from the already-redacted task title and
result summary supplied by :mod:`nexora.storage.artifacts`.
"""

from __future__ import annotations

import hashlib
import io
import json
import re
import zipfile
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any


DOCUMENT_FORMATS = ("docx", "pdf")
SPREADSHEET_HINTS = (
    "xlsx", "excel", "spreadsheet", "таблиц", "бюджет", "смет", "метрик",
    "аналитик", "финансов", "расход", "доход",
)
ARCHIVE_HINTS = (
    "zip", "archive", "архив", "пакет файлов", "исходник", "исходн",
    "проект с файлами", "комплект файлов",
)
ASSET_ROOT = Path(__file__).with_name("assets")
PDF_FONT = ASSET_ROOT / "DejaVuSans.ttf"


class DocumentRenderError(RuntimeError):
    """A rich document could not be rendered safely."""


def selected_formats(title: str, result: str) -> tuple[str, ...]:
    """Return deterministic formats for a completed task.

    DOCX and PDF are useful safe defaults for every completed task. XLSX and
    ZIP are opt-in based on explicit task/result intent to avoid producing
    misleading spreadsheets or archives.
    """

    haystack = f"{title}\n{result[:4000]}".casefold()
    formats = list(DOCUMENT_FORMATS)
    if any(value in haystack for value in SPREADSHEET_HINTS):
        formats.append("xlsx")
    if any(value in haystack for value in ARCHIVE_HINTS):
        formats.append("zip")
    return tuple(formats)


def required_artifact_formats(title: str, result: str) -> tuple[str, ...]:
    """Return every artifact kind required before a task may complete."""

    return ("markdown", "json", *selected_formats(title, result))


def _plain_lines(value: str) -> list[str]:
    lines = []
    for raw in str(value or "").replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", raw).strip()
        if line:
            lines.append(line[:4000])
    return lines or ["Результат не содержит отображаемого текста."]


def render_docx(task: dict[str, Any]) -> bytes:
    """Render a polished Word business brief using the pinned python-docx."""

    try:
        from docx import Document
        from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn
        from docx.shared import Inches, Pt, RGBColor
    except ImportError as exc:  # pragma: no cover - deployment dependency gate
        raise DocumentRenderError("DOCX renderer dependency is unavailable") from exc

    title = str(task["title"])
    task_id = str(task["task_id"])
    result = str(task["result"])
    document = Document()
    section = document.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(1)
    section.right_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.header_distance = Inches(0.492)
    section.footer_distance = Inches(0.492)

    def set_font(run: Any, size: float, *, bold: bool = False, color: str = "1F2937") -> None:
        run.font.name = "Calibri"
        run._element.get_or_add_rPr().rFonts.set(qn("w:ascii"), "Calibri")
        run._element.get_or_add_rPr().rFonts.set(qn("w:hAnsi"), "Calibri")
        run._element.get_or_add_rPr().rFonts.set(qn("w:eastAsia"), "Calibri")
        run.font.size = Pt(size)
        run.bold = bold
        run.font.color.rgb = RGBColor.from_string(color)

    normal = document.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.10
    for style_name, size, before, after, color in (
        ("Heading 1", 16, 16, 8, "2E74B5"),
        ("Heading 2", 13, 12, 6, "2E74B5"),
        ("Heading 3", 12, 8, 4, "1F4D78"),
    ):
        style = document.styles[style_name]
        style.font.name = "Calibri"
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor.from_string(color)
        style.paragraph_format.space_before = Pt(before)
        style.paragraph_format.space_after = Pt(after)

    header = section.header.paragraphs[0]
    header.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_font(header.add_run("NEXORA · РЕЗУЛЬТАТ ЗАДАЧИ"), 9, bold=True, color="6B7280")
    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    set_font(footer.add_run(f"{task_id} · Generated by Nexora"), 8.5, color="6B7280")

    kicker = document.add_paragraph()
    kicker.paragraph_format.space_after = Pt(2)
    set_font(kicker.add_run("NEXORA RESULT"), 9, bold=True, color="2E74B5")
    title_paragraph = document.add_paragraph()
    title_paragraph.paragraph_format.space_after = Pt(8)
    set_font(title_paragraph.add_run(title), 23, bold=True, color="111827")
    subtitle = document.add_paragraph()
    subtitle.paragraph_format.space_after = Pt(14)
    set_font(subtitle.add_run("Безопасный итог выполнения задачи"), 12, color="4B5563")

    table = document.add_table(rows=3, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    table.autofit = False
    table.columns[0].width = Inches(1.875)
    table.columns[1].width = Inches(4.625)
    for row, (label, value) in zip(
        table.rows,
        (
            ("Task ID", task_id),
            ("Status", "COMPLETED"),
            ("Completed", str(task.get("completed_at") or "—")[:32]),
        ),
    ):
        for index, width in enumerate((Inches(1.875), Inches(4.625))):
            row.cells[index].width = width
            row.cells[index].vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
            margins = row.cells[index]._tc.get_or_add_tcPr()
            tc_mar = margins.find(qn("w:tcMar"))
            if tc_mar is None:
                tc_mar = OxmlElement("w:tcMar")
                margins.append(tc_mar)
            for edge in ("top", "bottom", "start", "end"):
                node = tc_mar.find(qn(f"w:{edge}"))
                if node is None:
                    node = OxmlElement(f"w:{edge}")
                    tc_mar.append(node)
                node.set(qn("w:w"), "120" if edge in {"start", "end"} else "80")
                node.set(qn("w:type"), "dxa")
        set_font(row.cells[0].paragraphs[0].add_run(label), 10, bold=True, color="374151")
        set_font(row.cells[1].paragraphs[0].add_run(value), 10, color="111827")
    shading = table.rows[0].cells[0]._tc.get_or_add_tcPr()
    fill = OxmlElement("w:shd")
    fill.set(qn("w:fill"), "F2F4F7")
    shading.append(fill)

    document.add_heading("Результат", level=1)
    for line in _plain_lines(result):
        if line.startswith(("- ", "• ")):
            paragraph = document.add_paragraph(style="List Bullet")
            paragraph.paragraph_format.left_indent = Inches(0.5)
            paragraph.paragraph_format.first_line_indent = Inches(-0.25)
            paragraph.paragraph_format.space_after = Pt(8)
            set_font(paragraph.add_run(line[2:].strip()), 11)
        elif re.match(r"^\d+[.)]\s+", line):
            paragraph = document.add_paragraph(style="List Number")
            paragraph.paragraph_format.left_indent = Inches(0.5)
            paragraph.paragraph_format.first_line_indent = Inches(-0.25)
            paragraph.paragraph_format.space_after = Pt(8)
            set_font(paragraph.add_run(re.sub(r"^\d+[.)]\s+", "", line)), 11)
        elif line.startswith("### "):
            document.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            document.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            document.add_heading(line[2:], level=1)
        else:
            paragraph = document.add_paragraph()
            set_font(paragraph.add_run(line), 11)

    properties = document.core_properties
    properties.title = title[:255]
    properties.subject = "Nexora task result"
    properties.author = "Nexora"
    properties.keywords = "Nexora, task result"
    output = io.BytesIO()
    document.save(output)
    payload = output.getvalue()
    _verify_ooxml(payload, "word/")
    return payload


def render_pdf(task: dict[str, Any]) -> bytes:
    """Render a Cyrillic-safe PDF with an embedded redistributable font."""

    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_RIGHT
        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except ImportError as exc:  # pragma: no cover - deployment dependency gate
        raise DocumentRenderError("PDF renderer dependency is unavailable") from exc
    if not PDF_FONT.is_file():
        raise DocumentRenderError("PDF font asset is unavailable")

    font_name = "NexoraDejaVu"
    if font_name not in pdfmetrics.getRegisteredFontNames():
        pdfmetrics.registerFont(TTFont(font_name, str(PDF_FONT)))
    output = io.BytesIO()
    document = SimpleDocTemplate(
        output,
        pagesize=LETTER,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
        title=str(task["title"])[:255],
        author="Nexora",
        subject="Nexora task result",
    )
    styles = getSampleStyleSheet()
    body = ParagraphStyle(
        "NexoraBody",
        parent=styles["BodyText"],
        fontName=font_name,
        fontSize=10.5,
        leading=14,
        spaceAfter=7,
        textColor=colors.HexColor("#1F2937"),
    )
    title_style = ParagraphStyle(
        "NexoraTitle",
        parent=body,
        fontSize=22,
        leading=27,
        spaceAfter=10,
        textColor=colors.HexColor("#111827"),
    )
    heading = ParagraphStyle(
        "NexoraHeading",
        parent=body,
        fontSize=15,
        leading=19,
        spaceBefore=12,
        spaceAfter=8,
        textColor=colors.HexColor("#2E74B5"),
    )
    footer = ParagraphStyle("NexoraFooter", parent=body, fontSize=7.5, alignment=TA_RIGHT, textColor=colors.HexColor("#6B7280"))
    story = [
        Paragraph("NEXORA · РЕЗУЛЬТАТ ЗАДАЧИ", ParagraphStyle("Kicker", parent=body, fontSize=8.5, textColor=colors.HexColor("#2E74B5"))),
        Paragraph(escape(str(task["title"])), title_style),
        Table(
            [
                ["Task ID", str(task["task_id"])],
                ["Status", "COMPLETED"],
                ["Completed", str(task.get("completed_at") or "—")[:32]],
            ],
            colWidths=[1.45 * inch, 5.05 * inch],
            style=TableStyle(
                [
                    ("FONTNAME", (0, 0), (-1, -1), font_name),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#374151")),
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F2F4F7")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D1D5DB")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 7),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            ),
        ),
        Spacer(1, 12),
        Paragraph("Результат", heading),
    ]
    for line in _plain_lines(str(task["result"])):
        if line.startswith(("# ", "## ", "### ")):
            story.append(Paragraph(escape(line.lstrip("#").strip()), heading))
            continue
        prefix = "• " if line.startswith(("- ", "• ")) else ""
        content = line[2:].strip() if prefix else line
        story.append(Paragraph(escape(prefix + content), body))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"{escape(str(task['task_id']))} · Generated by Nexora", footer))
    document.build(story)
    payload = output.getvalue()
    if not payload.startswith(b"%PDF-") or b"/JavaScript" in payload or b"/Launch" in payload:
        raise DocumentRenderError("generated PDF failed safety validation")
    return payload


def render_xlsx(task: dict[str, Any]) -> bytes:
    """Create a macro-free, formula-free single-sheet OOXML workbook."""

    rows = [
        ("Поле", "Значение"),
        ("Task ID", str(task["task_id"])),
        ("Название", str(task["title"])),
        ("Статус", "COMPLETED"),
        ("Завершена", str(task.get("completed_at") or "—")[:32]),
        ("Результат", str(task["result"])),
    ]

    def cell(reference: str, value: str, style: int = 0) -> str:
        return f'<c r="{reference}" t="inlineStr" s="{style}"><is><t xml:space="preserve">{escape(value)}</t></is></c>'

    sheet_rows = []
    for index, (label, value) in enumerate(rows, start=1):
        style = 1 if index == 1 else 2 if index <= 5 else 3
        sheet_rows.append(
            f'<row r="{index}" ht="{30 if index == 1 else 22}" customHeight="1">'
            f'{cell(f"A{index}", label, style)}{cell(f"B{index}", value, style)}</row>'
        )
    files = {
        "[Content_Types].xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            '<Default Extension="xml" ContentType="application/xml"/>'
            '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
            '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
            '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
            '<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>'
            '<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>'
            '</Types>'
        ),
        "_rels/.rels": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
            '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>'
            '<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>'
            '</Relationships>'
        ),
        "xl/workbook.xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
            'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
            '<sheets><sheet name="Результат" sheetId="1" r:id="rId1"/></sheets></workbook>'
        ),
        "xl/_rels/workbook.xml.rels": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
            '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
            '</Relationships>'
        ),
        "xl/worksheets/sheet1.xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            '<sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>'
            '<cols><col min="1" max="1" width="22" customWidth="1"/><col min="2" max="2" width="80" customWidth="1"/></cols>'
            f'<sheetData>{"".join(sheet_rows)}</sheetData>'
            '<autoFilter ref="A1:B6"/></worksheet>'
        ),
        "xl/styles.xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            '<fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos Display"/></font></fonts>'
            '<fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1F4E78"/><bgColor indexed="64"/></patternFill></fill></fills>'
            '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>'
            '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
            '<cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'
            '<xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center"/></xf>'
            '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf>'
            '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs>'
            '<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'
        ),
        "docProps/core.xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
            'xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" '
            'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
            f'<dc:title>{escape(str(task["title"]))}</dc:title><dc:creator>Nexora</dc:creator>'
            f'<dcterms:created xsi:type="dcterms:W3CDTF">{datetime.now(timezone.utc).isoformat()}</dcterms:created>'
            '</cp:coreProperties>'
        ),
        "docProps/app.xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">'
            '<Application>Nexora</Application></Properties>'
        ),
    }
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as workbook:
        for name, content in files.items():
            workbook.writestr(name, content.encode("utf-8"))
    payload = output.getvalue()
    _verify_ooxml(payload, "xl/")
    return payload


def render_zip(task: dict[str, Any], members: dict[str, bytes]) -> bytes:
    """Bundle already-rendered safe artifacts with a checksum manifest."""

    safe_members = {
        name: bytes(payload)
        for name, payload in members.items()
        if re.fullmatch(r"result\.(?:md|json|docx|xlsx|pdf)", name)
    }
    manifest = {
        "task_id": str(task["task_id"]),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "files": [
            {"name": name, "size_bytes": len(payload), "sha256": hashlib.sha256(payload).hexdigest()}
            for name, payload in sorted(safe_members.items())
        ],
    }
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, payload in sorted(safe_members.items()):
            info = zipfile.ZipInfo(name)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o600 << 16
            archive.writestr(info, payload)
        info = zipfile.ZipInfo("MANIFEST.json")
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = 0o600 << 16
        archive.writestr(info, json.dumps(manifest, ensure_ascii=False, indent=2).encode("utf-8"))
    payload = output.getvalue()
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        if any(name.startswith(("/", "\\")) or ".." in Path(name).parts for name in archive.namelist()):
            raise DocumentRenderError("generated archive failed path validation")
    return payload


def _verify_ooxml(payload: bytes, required_prefix: str) -> None:
    if not zipfile.is_zipfile(io.BytesIO(payload)):
        raise DocumentRenderError("generated Office document is not a valid package")
    with zipfile.ZipFile(io.BytesIO(payload)) as package:
        names = package.namelist()
        if not any(name.startswith(required_prefix) for name in names):
            raise DocumentRenderError("generated Office document is incomplete")
        if any(name.casefold().endswith(("vbaproject.bin", ".exe", ".dll", ".js", ".ps1", ".sh")) for name in names):
            raise DocumentRenderError("generated Office document contains executable content")
        for name in names:
            if name.endswith(".rels"):
                content = package.read(name).decode("utf-8", errors="ignore").casefold()
                if 'targetmode="external"' in content:
                    raise DocumentRenderError("external Office relationships are not allowed")


def render_rich_artifacts(task: dict[str, Any], base_members: dict[str, bytes]) -> dict[str, bytes]:
    """Render the selected safe rich formats for one completed task."""

    rendered: dict[str, bytes] = {}
    formats = selected_formats(str(task["title"]), str(task["result"]))
    if "docx" in formats:
        rendered["docx"] = render_docx(task)
    if "pdf" in formats:
        rendered["pdf"] = render_pdf(task)
    if "xlsx" in formats:
        rendered["xlsx"] = render_xlsx(task)
    if "zip" in formats:
        members = {f"result.{kind if kind != 'markdown' else 'md'}": value for kind, value in {**base_members, **rendered}.items()}
        rendered["zip"] = render_zip(task, members)
    return rendered
