PRAGMA foreign_keys = OFF;
DROP INDEX IF EXISTS idx_tasks_workspace_updated;
DROP INDEX IF EXISTS idx_activity_workspace_created;
DROP INDEX IF EXISTS idx_comments_workspace_task;
DROP INDEX IF EXISTS idx_knowledge_workspace_created;
DROP INDEX IF EXISTS idx_workspace_members_user_status;
DROP INDEX IF EXISTS idx_workspaces_org_status;
DROP INDEX IF EXISTS idx_organizations_owner_status;
DROP TABLE IF EXISTS activity_events;
DROP TABLE IF EXISTS task_comments;
DROP TABLE IF EXISTS knowledge_documents;
DROP TABLE IF EXISTS workspace_skills;
DROP TABLE IF EXISTS workspace_agents;
DROP TABLE IF EXISTS workspace_members;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS organizations;
ALTER TABLE tasks DROP COLUMN assignee_id;
ALTER TABLE tasks DROP COLUMN creator_id;
ALTER TABLE tasks DROP COLUMN workspace_id;
ALTER TABLE tasks DROP COLUMN organization_id;
DROP INDEX IF EXISTS idx_users_email_hash;
ALTER TABLE users DROP COLUMN display_name;
ALTER TABLE users DROP COLUMN email_hash;
DELETE FROM schema_migrations WHERE version = 6;
PRAGMA foreign_keys = ON;
